name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Enable corepack
        run: corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🏗 Build
        run: pnpm run build

      - uses: actions/checkout@v4
      - name: 🚀 Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
