[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 3000

[context.dev]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    "Content-Type" = "application/manifest+json"
