"overrides":
  "axios@>=0.8.1 <0.28.0": ">=0.28.0"
  "rollup@<2.79.2": ">=2.79.2"
  "cookie@<0.7.0": ">=0.7.0"
  "esbuild@<=0.24.2": ">=0.25.0"
  "axios@<0.30.0": ">=0.30.0"

"onlyBuiltDependencies":
  - "@tailwindcss/oxide"
