name = "personal-website"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[observability]
enabled = true

[site]
bucket = "./build/client"

[build]
command = "pnpm run build"

browser = { binding = "MYBROWSER" }
