name: ♻️ Purge Cloudflare cache

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  purge:
    name: ♻️ Purge Cloudflare cache
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: 📦 Build current commit
        run: |
          pnpm run build
          mv ./build ./current

      - name: 📦 Build previous commit
        run: |
          git checkout HEAD^
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm run build
          mv ./build ./previous

      - name: ♻️ Get URLs to Purge
        id: urls
        run: |
          URLS=$(node ./scripts/get-urls-to-purge.js)
          echo "urls=$URLS" >> $GITHUB_ENV

      - name: ♻️ Purge Cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        if: steps.urls.outputs.urls != ''
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          PURGE_URLS: ${{ steps.urls.outputs.urls }}
